In [1]:
print('Shaon Khan')

Shaon Khan

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [3]:
arr_2d = np.array([[1,2,3],[4,5,6],[1,2,8]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 8]])

In [4]:
arr_2d.shape

(3, 3)

In [5]:
arr.shape

(5,)

In [6]:
arr[1]

np.int64(20)

In [7]:
arr_2d[1:3, 0:2]

array([[4, 5],
       [1, 2]])

In [8]:
zero_arr = np.zeros((3,4))
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
zero_ar = np.zeros(20)
zero_ar.reshape(5,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.full((2,3),1)

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
np.full((2,7),71)

array([[71, 71, 71, 71, 71, 71, 71],
       [71, 71, 71, 71, 71, 71, 71]])

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
ran_arr = np.random.rand(4,2)
ran_arr

array([[0.23427482, 0.89028795],
       [0.00634672, 0.76523231],
       [0.13883769, 0.10254013],
       [0.62282107, 0.55229829]])

In [15]:
np.random.randint(3,10,(2,3))

array([[7, 3, 7],
       [3, 9, 3]], dtype=int32)

In [16]:
np.random.randint(3,100)

79

In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(2,11,3)

array([2, 5, 8])

In [19]:
np.sum(arr)

np.int64(150)

In [20]:
np.mean(arr)

np.float64(30.0)

In [21]:
np.min(arr)

np.int64(10)

In [22]:
np.max(arr)

np.int64(50)

In [23]:
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [24]:
np.std(arr)

np.float64(14.142135623730951)

In [25]:
np.sin(arr)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [26]:
one = np.ones((3,4))
one[1] = 123
one

array([[  1.,   1.,   1.,   1.],
       [123., 123., 123., 123.],
       [  1.,   1.,   1.,   1.]])

In [27]:
fileread = np.genfromtxt('data.csv', delimiter = ',')
fileread

array([[ nan,  nan,  nan,  nan],
       [ 1. ,  nan, 23. , 85.5],
       [ 2. ,  nan, 25. , 90. ],
       [ 3. ,  nan, 22. , 78. ],
       [ 4. ,  nan, 24. , 88.5],
       [ 5. ,  nan, 21. , 92. ]])

In [28]:
new_col = fileread[::,3:4]
new_col.dtype

dtype('float64')

In [29]:
new_col.astype('int64')

C:\Users\HP\AppData\Local\Temp\ipykernel_17236\1784736309.py:1: RuntimeWarning: invalid value encountered in cast
  new_col.astype('int64')

array([[-9223372036854775808],
       [                  85],
       [                  90],
       [                  78],
       [                  88],
       [                  92]])

In [30]:
# from numpy import loadtxt

# csvread = open('data.csv','rb')
# read = loadtxt(csvread, delimiter = ',')
# read

In [31]:
import pandas as pd

dataset = {
    'Name': ['Shaon','Sadia','Ayan','Shahanaz','Monzu'],
    'Age': [22, 21, 9, 38, 48]
}
df = pd.DataFrame(dataset)
df

       Name  Age
0     Shaon   22
1     Sadia   21
2      Ayan    9
3  Shahanaz   38
4     Monzu   48

In [32]:
df = [1,2,3,4,5]

In [33]:
df = pd.Series(df, index = ['a','b','c','d','e'])
df

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [34]:
import pandas as pd

dataset = {
    'Name': ['Shaon','Sadia','Ayan','Shahanaz','Monzu'],
    'Age': [22, 21, 9, 38, 48]
}
df = pd.DataFrame(dataset)
df

       Name  Age
0     Shaon   22
1     Sadia   21
2      Ayan    9
3  Shahanaz   38
4     Monzu   48

In [35]:
df.loc[[0,3]]

       Name  Age
0     Shaon   22
3  Shahanaz   38

In [36]:
dataset = {
    'Name': ['Shaon','Sadia','Ayan','Shahanaz','Monzu'],
    'Age': [22, 21, 9, 38, 48]
}

In [37]:
df1 = pd.DataFrame(dataset, index = ['i','ii','iii','iv','v'])
df1

         Name  Age
i       Shaon   22
ii      Sadia   21
iii      Ayan    9
iv   Shahanaz   38
v       Monzu   48

In [45]:
arr = np.array([{10,12,13},{1,2,3},{5,6,7}])
arr.ndim

1

In [46]:
arr

array([{10, 12, 13}, {1, 2, 3}, {5, 6, 7}], dtype=object)

In [47]:
arr = np.array([[10,12,13],[1,2,3],[5,6,7]])

arr.shape

(3, 3)

In [48]:
arr

array([[10, 12, 13],
       [ 1,  2,  3],
       [ 5,  6,  7]])